packages:
  - "backend"
  - "mobile"
  - "backoffice"
  - "packages/*"

allowBuilds:
  '@scarf/scarf': false
  argon2: true
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  workerd: false
  unrs-resolver: false
