export const AttendanceReasonCode = {
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REPLAYED: "TOKEN_REPLAYED",
  SCANNER_NOT_AUTHORIZED: "SCANNER_NOT_AUTHORIZED",
  SESSION_CANCELLED: "SESSION_CANCELLED",
  OUTSIDE_WINDOW: "OUTSIDE_WINDOW",
  NO_BOOKING: "NO_BOOKING",
  BOOKING_WAITLISTED: "BOOKING_WAITLISTED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  ALREADY_CHECKED_IN: "ALREADY_CHECKED_IN",
  MEMBERSHIP_EXPIRED: "MEMBERSHIP_EXPIRED",
  MEMBERSHIP_SUSPENDED: "MEMBERSHIP_SUSPENDED",
  PLAN_NOT_VALID_AT_BRANCH: "PLAN_NOT_VALID_AT_BRANCH",
} as const;

export type AttendanceReasonCode = (typeof AttendanceReasonCode)[keyof typeof AttendanceReasonCode];

export const AccessReasonCode = {
  ...AttendanceReasonCode,
  CROSS_BRANCH_BOOKING_DISABLED: "CROSS_BRANCH_BOOKING_DISABLED",
  CROSS_BRANCH_QUOTA_EXCEEDED: "CROSS_BRANCH_QUOTA_EXCEEDED",
  CROSS_BRANCH_WINDOW_NOT_OPEN: "CROSS_BRANCH_WINDOW_NOT_OPEN",
  SESSION_FULL: "SESSION_FULL",
  NO_SHOW_PENALTY_ACTIVE: "NO_SHOW_PENALTY_ACTIVE",
  OK: "OK",
} as const;

export type AccessReasonCode = (typeof AccessReasonCode)[keyof typeof AccessReasonCode];
